Repository cybertec-postgresql/pgwatch, pull requests merged in 2024-02, with the labels that each got.

#358 [!] decouple `sources` package from `main`, closes #357
  src/config/cmdoptions.go
  src/config/cmdparser.go
  src/config/consts.go
  src/config/sample.instances.yaml
  src/database.go
  src/logparse.go
  src/main.go
  src/metrics/types.go
  src/sinks/multiwriter.go
  src/sinks/prometheus.go
  src/sources/patroni.go
  src/sources/postgres.go
  src/sources/types.go
  src/sources/yaml.go
Labels: enhancement, epic, refactoring

#360 [+] bump `yaml.v2` to `yaml.v3`, closes #359
  src/go.mod
  src/go.sum
  src/metrics/io.go
  src/sources/types.go
  src/sources/yaml.go
Labels: dependencies, go

#363 [*] move `psutil` and `logparser` to `sources` package
  src/database.go
  src/log/formatter.go
  src/main.go
  src/metrics/logparse.go
  src/metrics/psutil/psutil.go
  src/metrics/psutil/psutil_darwin.go
  src/metrics/psutil/psutil_linux.go
  src/metrics/psutil/psutil_windows.go
  src/metrics/types.go
Labels: refactoring

#364 [*] refactor command-line parsing
  .github/workflows/build.yml
  .github/workflows/release.yml
  build-docker-demo.sh
  build-docker.sh
  docker/Dockerfile
  docker/demo/Dockerfile
  src/build.sh
  src/build_gatherer.sh
  src/config/cmdoptions.go
  src/config/cmdparser_test.go
  src/config/config_test.go
  src/go.mod
  src/main.go
Labels: docker, github_actions, refactoring

#367 [*] prettify `config`, remove unused opts
  src/config/cmdoptions.go
  src/config/cmdoptions_test.go
  src/config/cmdparser.go
  src/config/config_test.go
  src/main.go
Labels: refactoring

#368 [!] add `Measurements` group and use URIs for `--sink` options
  src/config/cmdoptions.go
  src/database.go
  src/db/conn.go
  src/log/formatter.go
  src/main.go
  src/sinks/json_file.go
  src/sinks/multiwriter.go
  src/sinks/postgres.go
  src/sinks/prometheus.go
  src/sources/postgres.go
  src/sources/yaml.go
Labels: refactoring

#369 [+] bump Node to v21, Postgres to v16, Grafana to v10.3 in docker images
  build-docker-demo.sh
  docker-compose.yml
  docker/Dockerfile
  docker/bootstrap/init_test_monitored_db.sh
  docker/demo/Dockerfile
Labels: dependencies, docker

#371 [*] remove deprecated helpers
  src/metrics/sql/00_helpers/get_sequences/10/metric.sql
  src/metrics/sql/00_helpers/get_stat_activity/9.0/metric.sql
  src/metrics/sql/00_helpers/get_stat_activity/9.2/metric.sql
  src/metrics/sql/00_helpers/get_stat_replication/9.2/metric.sql
  src/metrics/sql/00_helpers/get_stat_statements/9.2/metric.sql
  src/metrics/sql/00_helpers/get_stat_statements/9.4/metric.sql
  src/metrics/sql/00_helpers/get_table_bloat_approx_sql/9.0/metric.sql
  src/metrics/sql/00_helpers/get_wal_size/10/metric.sql
  src/metrics/sql/00_helpers/get_wal_size/9.0/metric.sql
Labels: refactoring

#374 [+] move helpers to metrics definition
  src/metrics/convert/convert.go
Labels: metrics, refactoring

#377 [-] fix typo
  docs/advanced_features.rst
Labels: documentation
