Repository cybertec-postgresql/pgwatch, pull requests merged in 2024-07, with the labels that each got.

#472 [!] differentiate the concepts of source and monitored database
  src/reaper/database.go
  src/reaper/reaper.go
  src/sources/postgres.go
  src/sources/postgres_test.go
  src/sources/resolver.go
  src/sources/resolver_test.go
  src/sources/types.go
  src/sources/types_test.go
  src/sources/yaml.go
  src/sources/yaml_test.go
  src/webserver/api.go
  src/webserver/source.go
Labels: enhancement

#465 [!] add RPC sink support, closes #464
  src/sinks/multiwriter.go
  src/sinks/rpc.go
  src/sinks/rpc_test.go
Labels: enhancement

#475 [*] add description to sink implementations
  src/go.mod
  src/go.sum
  src/sinks/doc.go
  src/sinks/json.go
  src/sinks/postgres.go
  src/sinks/prometheus.go
  src/sinks/rpc.go
Labels: documentation, dependencies, go

#476 [!] transform `Sphinx` manual to `mkdocs-material`
  .github/workflows/build.yml
  docs/Makefile
  docs/README.md
  docs/README.rst
  docs/advanced_features.md
  docs/advanced_features.rst
  docs/components.md
  docs/components.rst
  docs/conf.py
  docs/custom_installation.md
  docs/custom_installation.rst
  docs/dashboarding_alerting.md
  docs/dashboarding_alerting.rst
  docs/docker_installation.md
  docs/docker_installation.rst
  docs/features.md
  docs/features.rst
  docs/gallery.md
  docs/index.rst
  docs/installation_options.md
  docs/installation_options.rst
  docs/kubernetes.md
  docs/kubernetes.rst
  docs/long_term_installations.md
  docs/long_term_installations.rst
  docs/metric_definitions.md
  docs/metric_definitions.rst
  docs/preparing_databases.md
  docs/preparing_databases.rst
  docs/project_background.md
  docs/project_background.rst
  docs/screenshots/pgwatch3_architecture.png
  docs/screenshots/pgwatch3_architecture_push.png
  docs/screenshots/pgwatch3_change_detected_dash.png
  docs/screenshots/webui_logs.png
  docs/screenshots/webui_metrics_grid.png
  docs/screenshots/webui_presets_grid.png
  docs/screenshots/webui_sources_grid.png
  docs/security.md
  docs/security.rst
  docs/sizing_recommendations.md
  docs/sizing_recommendations.rst
  docs/technical_details.md
  docs/technical_details.rst
  docs/upgrading.md
  docs/upgrading.rst
  docs/using_managed_services.md
  docs/using_managed_services.rst
  docs/web_ui.md
  docs/web_ui.rst
  mkdocs.yml
Labels: documentation

#477 [*] move docker scripts to appropriate folder
  .github/workflows/build.yml
  docker/build-docker-demo.sh
  docker/build-docker.sh
Labels: docker

#479 [*] move metric conversion utility from the main tree
  utils/convert/convert.go
  utils/convert/go.mod
  utils/convert/go.sum
Labels: metrics, refactoring

#478 [+] add metrics tests
  src/db/bootstrap_test.go
  src/go.mod
  src/go.sum
  src/metrics/default_test.go
  src/metrics/postgres.go
  src/metrics/postgres_schema.go
  src/metrics/postgres_schema_test.go
  src/metrics/postgres_test.go
  src/metrics/psutil/psutil.go
  src/metrics/psutil/psutil_test.go
  src/metrics/types.go
  src/metrics/types_test.go
  src/metrics/yaml.go
  src/metrics/yaml_test.go
  src/reaper/reaper.go
  src/sinks/postgres_test.go
  src/sources/postgres_test.go
Labels: test

#487 [+] improve Developer Documentation
  .gitignore
  CODE_OF_CONDUCT.md
  docs/CODE_OF_CONDUCT.md
  docs/LICENSE.md
  docs/contributing.md
  docs/godoc.md
  mkdocs.yml
  src/metrics/doc.go
  src/sinks/doc.go
Labels: documentation

#491 [-] fix metric version discovery for old PostgreSQL versions, fixes #489
  src/reaper/cache.go
  src/reaper/database.go
  src/reaper/file.go
  src/reaper/reaper.go
  src/reaper/recommendations.go
  src/reaper/types.go
Labels: bug

#495 [-] fix version detection for pre-16 PostgreSQL, closes #494
  src/reaper/database.go
Labels: bug
