Repository cybertec-postgresql/pgwatch, pull requests merged in 2024-03, with the labels that each got.

#382 [*] remove references to deprecated metric files from docker-compose.yml
  docker-compose.yml
  docker/bootstrap/2_init_pgwatch_db.sh
Labels: bug, docker

#386 [+] bump go dependencies
  src/go.mod
  src/go.sum
Labels: dependencies, go

#395 [-] fix JSON format issue causing webpage loading failure
  src/api.go
Labels: bug, webui

#392 [*] use Docker Compose V2 instead of V1
  README.md
Labels: documentation

#397 [+] add test cases to webserver api
  src/webserver/server_test.go
Labels: test, webui

#388 [-] fix possible index out of bound issue, fixes #387
  src/log/log_broker_hook.go
  src/log/log_broker_hook_test.go
Labels: bug

#398 [*] update docker compose command to force recreate test database
  README.md
Labels: documentation

#400 [-] fix deprecated dependencies on WebUI
  src/webui/.eslintignore
  src/webui/src/layout/Logs/LogGrid/logOutput.tsx
  src/webui/tsconfig.json
Labels: webui

#402 [-] if presets are used then skip single metric checks, fixes #401
  src/config/cmdoptions.go
  src/main.go
  src/metrics/postgres.go
  src/metrics/yaml.go
  src/metrics/yaml_test.go
  src/sources/postgres.go
Labels: bug
