Repository cybertec-postgresql/pgwatch, pull requests merged in 2024-04, with the labels that each got.

#419 [!] move measurements reaper code out of main package, closes #418
  src/go.mod
  src/go.sum
  src/main.go
  src/reaper/cache.go
  src/reaper/database.go
  src/reaper/file.go
  src/reaper/reaper.go
  src/reaper/recommendations.go
  src/reaper/types.go
  src/reaper/version_test.go
Labels: refactoring

#427 [-] update README for measurements database schema, closes #423
  src/db/sql/metric/README.md
Labels: documentation

#428 [*] update environment variables documentation, closes #424
  docker/bootstrap/init_dbs.sh
  docs/ENV_VARIABLES.md
  src/config/cmdoptions.go
  src/main.go
Labels: documentation

#432 [+] add pgAdmin4 to `docker-compose.yml`
  README.md
  docker-compose.yml
  docker/pgadmin_pass
  docker/pgadmin_servers.json
Labels: enhancement, docker

#435 [+] get rid of control channel map, closes #434
  src/metrics/logparse.go
  src/metrics/types.go
  src/reaper/reaper.go
Labels: refactoring

#436 [*] improve `--help` output
  src/config/cmdoptions.go
  src/config/cmdoptions_test.go
  src/main.go
Labels: refactoring

#407 [!] bump Grafana to v11
  docker-compose.yml
  grafana/postgres/v11/1-global-db-overview.json
  grafana/postgres/v11/alert-template.json
  grafana/postgres/v11/aws-cloudwatch.json
  grafana/postgres/v11/biggest-relations.json
  grafana/postgres/v11/change-events.json
  grafana/postgres/v11/checkpointer-bgwriter-stats.json
  grafana/postgres/v11/db-overview-developer.json
  grafana/postgres/v11/db-overview-time-lag.json
  grafana/postgres/v11/db-overview.json
  grafana/postgres/v11/documentation.json
  grafana/postgres/v11/global-health.json
  grafana/postgres/v11/health-check.json
  grafana/postgres/v11/index-overview.json
  grafana/postgres/v11/lock-details.json
  grafana/postgres/v11/pgbouncer-stats.json
  grafana/postgres/v11/pgpool-stats.json
  grafana/postgres/v11/postgres-version-overview.json
  grafana/postgres/v11/recommendations.json
  grafana/postgres/v11/replication.json
  grafana/postgres/v11/server-log-events.json
  grafana/postgres/v11/sessions-overview.json
  grafana/postgres/v11/show-plans-realtime.json
  grafana/postgres/v11/single-query-details.json
  grafana/postgres/v11/sproc-details.json
  grafana/postgres/v11/sprocs-top.json
  grafana/postgres/v11/stat-activity-realtime.json
  grafana/postgres/v11/stat-activity.json
  grafana/postgres/v11/stat-statements-sql-search.json
  grafana/postgres/v11/stat-statements-top-fast.json
  grafana/postgres/v11/stat-statements-top-visual.json
  grafana/postgres/v11/stat-statements-top.json
  grafana/postgres/v11/system-stats-time-lag.json
  grafana/postgres/v11/system-stats.json
  grafana/postgres/v11/table-details-time-lag.json
  grafana/postgres/v11/table-details.json
  grafana/postgres/v11/tables-top.json
  grafana/postgres_datasource.yml
  grafana/prometheus/v11/db-overview.json
  grafana/prometheus/v11/health-check.json
  grafana/prometheus/v11/sessions-overview.json
  grafana/prometheus/v11/table-details.json
  grafana/prometheus/v11/tables-top.json
Labels: enhancement, dashboards, docker
