Repository cybertec-postgresql/pgwatch, pull requests merged in 2024-11, with the labels that each got.

#580 Remove hardcoded pgwatch user in config schema creation
  internal/metrics/postgres_schema.sql
Labels: enhancement

#587 [+] improve `docker compose` files
  docker/Dockerfile.postgres-plpython3u
  docker/compose.add-test-db.sh
  docker/compose.add-test-db.yml
  docker/compose.pgactivity.sh
  docker/compose.pgbench.sh
  docker/compose.pgbench.yml
  docker/compose.postgres.yml
  docker/compose.timescaledb.yml
Labels: enhancement, docker

#588 [+] add "Bootstrapping the Measurements Database" how-to, closes #567
  docs/howto/metrics_db_bootstrap.md
  internal/sinks/multiwriter.go
  internal/sinks/postgres.go
  mkdocs.yml
Labels: documentation

#592 [+] add sample configuration YAML files to release assets
  .goreleaser.yml
Labels: enhancement
