Repository cybertec-postgresql/pgwatch, pull requests merged in 2024-10, with the labels that each got.

#555 [+] bump Go to v1.23
  .github/workflows/build.yml
  .github/workflows/release.yml
  docker/Dockerfile
  docker/demo/Dockerfile
  go.mod
Labels: dependencies, go

#558 [*] replace `--no-helper-functions` with `--create-helpers` , closes #557
  internal/metrics/cmdopts.go
  internal/reaper/reaper.go
  internal/sinks/multiwriter.go
Labels: enhancement

#559 [-] fix connection string used for resolved databases, fixes #554
  internal/db/bootstrap.go
  internal/sources/types.go
Labels: bug

#560 [-] apply `--max-parallel-connections-per-db` for connections
  internal/reaper/reaper.go
  internal/sinks/cmdopts.go
  internal/sources/cmdopts.go
  internal/sources/types.go
  internal/sources/types_test.go
Labels: bug

#565 [-] add execute permissions for bootstrap Docker scripts, fixes #562
  README.md
  docker/bootstrap/init_dbs.sh
  docker/bootstrap/init_persistent_config.sh
  docker/bootstrap/init_supervisor.sh
  docker/bootstrap/init_test_monitored_db.sh
Labels: bug, docker

#575 [-] fix non-Latin field name
  internal/sinks/postgres.go
  internal/sinks/postgres_test.go
Labels: bug

#572 [-] fix minor typo
  internal/sources/doc.go
Labels: documentation

#576 [+] disable web user interface if `--web-addr` is empty
  internal/cmdopts/cmdoptions.go
Labels: enhancement

#578 [*] improve Prometheus sink and Docker setup docs
  docs/reference/advanced_features.md
  docs/tutorial/custom_installation.md
  docs/tutorial/docker_installation.md
  internal/sinks/cmdopts.go
Labels: documentation
