Repository cybertec-postgresql/pgwatch, pull requests merged in 2025-06, with the labels that each got.

#775 [*] use `pgx.Rows` directly in `DetectConfigurationChanges()`
  internal/reaper/database.go
Labels: metrics, refactoring

#776 [+] switch to `json-iterator/go` from `encoding/json`
  go.mod
  go.sum
  internal/db/conn.go
  internal/reaper/reaper.go
  internal/sinks/cmdopts.go
  internal/sinks/json.go
  internal/sinks/json_test.go
  internal/sources/resolver.go
  internal/webserver/jwt.go
  internal/webserver/jwt_test.go
  internal/webserver/metric.go
  internal/webserver/metric_test.go
  internal/webserver/server_test.go
  internal/webserver/source.go
  internal/webserver/source_test.go
  internal/webserver/webserver_test.go
Labels: refactoring

#779 [+] add `pprof` build profile for debugging
  cmd/pgwatch/main.go
  cmd/pgwatch/pprof.go
  docker/compose.pgwatch.yml
Labels: enhancement, go

#782 [+] add `DeleteOp` and `AddOp` consts to `api`
  api/types.go
Labels: enhancement

#790 [-] improve Prometheus scrapping, fixes #749
  internal/sinks/postgres.go
  internal/sinks/prometheus.go
Labels: bug, sinks

#791 [-] fix `instance_up` metric, closes #759
  internal/reaper/database.go
  internal/reaper/reaper.go
  internal/sinks/prometheus.go
Labels: bug, sinks

#794 [-] fix `--group` command-line option, closes #792
  internal/log/log.go
  internal/metrics/types.go
  internal/reaper/reaper.go
  internal/reaper/reaper_test.go
  internal/sources/conn.go
  internal/sources/conn_test.go
  internal/sources/postgres_test.go
Labels: bug, sources

#798 [*] add "default" group processing
  internal/reaper/reaper.go
  internal/reaper/reaper_test.go
  internal/sources/types.go
  internal/sources/types_test.go
Labels: bug

#796 [+] add TLS encryption to RPC channel
  internal/sinks/multiwriter.go
  internal/sinks/rpc.go
  internal/sinks/rpc_test.go
  internal/sinks/rpc_tests_certs/ca.crt
  internal/sinks/rpc_tests_certs/server.crt
  internal/sinks/rpc_tests_certs/server.key
  internal/sinks/types.go
Labels: enhancement, sinks

#807 [*] fix typo in `reapMetricMeasurements()` log message
  internal/reaper/reaper.go
Labels: documentation

#815 [*] fix `Reap()` method to update Recovery cache after processing the previous value
  internal/reaper/reaper.go
Labels: bug

#813 [*] fix `master only` postgres source shutdown due to catched `InRecovery` state logic
  internal/reaper/reaper.go
Labels: bug
