Repository cybertec-postgresql/pgwatch, pull requests merged in 2025-07, with the labels that each got.

#822 updating grafana postgres dashboards to v-12
  grafana/postgres/v12/biggest-relations.json
  grafana/postgres/v12/change-events.json
  grafana/postgres/v12/checkpointer-bgwriter-stats.json
  grafana/postgres/v12/global-health.json
  grafana/postgres/v12/health-check.json
  grafana/postgres/v12/index-overview.json
  grafana/postgres/v12/pgbouncer-stats.json
  grafana/postgres/v12/pgpool-stats.json
  grafana/postgres/v12/postgres-version-overview.json
  grafana/postgres/v12/recommendations.json
  grafana/postgres/v12/replication.json
  grafana/postgres/v12/server-log-events.json
  grafana/postgres/v12/sessions-overview.json
  grafana/postgres/v12/show-plans-realtime.json
  grafana/postgres/v12/single-query-details.json
  grafana/postgres/v12/sproc-details.json
  grafana/postgres/v12/sprocs-top.json
  grafana/postgres/v12/stat-activity-realtime.json
  grafana/postgres/v12/stat-activity.json
  grafana/postgres/v12/stat-statements-sql-search.json
  grafana/postgres/v12/stat-statements-top-fast.json
  grafana/postgres/v12/stat-statements-top-visual.json
  grafana/postgres/v12/stat-statements-top.json
  grafana/postgres/v12/system-stats-time-lag.json
  grafana/postgres/v12/system-stats.json
  grafana/postgres/v12/table-details-time-lag.json
  grafana/postgres/v12/table-details.json
  grafana/postgres/v12/tables-top.json
Labels: dashboards

#828 [*] improve `--batching-delay` parameter description, closes #821
  cmd/pgwatch/doc.go
  docs/howto/sizing_recommendations.md
  docs/reference/cli_env.md
  internal/cmdopts/cmdoptions.go
  internal/sinks/cmdopts.go
Labels: documentation

#831 [-] fix `Source.Equal()` presets comparison, closes #830
  internal/sources/types.go
  internal/sources/types_test.go
Labels: bug, sources

#838 [-] fix JSONB null casting errors in `postgres/v11` dashboards
  grafana/postgres/v11/1-global-db-overview.json
  grafana/postgres/v11/biggest-relations.json
  grafana/postgres/v11/change-events.json
  grafana/postgres/v11/checkpointer-bgwriter-stats.json
  grafana/postgres/v11/db-overview-developer.json
  grafana/postgres/v11/db-overview.json
  grafana/postgres/v11/global-health.json
  grafana/postgres/v11/index-overview.json
  grafana/postgres/v11/lock-details.json
  grafana/postgres/v11/postgres-version-overview.json
  grafana/postgres/v11/recommendations.json
  grafana/postgres/v11/replication.json
  grafana/postgres/v11/server-log-events.json
  grafana/postgres/v11/sessions-overview.json
  grafana/postgres/v11/show-plans-realtime.json
  grafana/postgres/v11/single-query-details.json
  grafana/postgres/v11/sproc-details.json
  grafana/postgres/v11/sprocs-top.json
  grafana/postgres/v11/stat-activity-realtime.json
  grafana/postgres/v11/stat-activity.json
  grafana/postgres/v11/stat-statements-sql-search.json
  grafana/postgres/v11/stat-statements-top-fast.json
  grafana/postgres/v11/system-stats-time-lag.json
  grafana/postgres/v11/system-stats.json
  grafana/postgres/v11/table-details-time-lag.json
  grafana/postgres/v11/table-details.json
  grafana/postgres/v11/tables-top.json
Labels: dashboards

#846 [*] improve stat-statements Grafana v11 Postgres dashboards
  docker/compose.grafana.yml
  grafana/postgres/v11/stat-statements-sql-search.json
  grafana/postgres/v11/stat-statements-top-visual.json
  grafana/postgres/v11/stat-statements-top.json
Labels: dashboards

#850 [!] migrate rpc sink to grpc
  .github/actions/setup-protobuf/action.yml
  .github/workflows/build.yml
  .github/workflows/release.yml
  .gitignore
  .goreleaser.yml
  api/pb/doc.go
  api/pb/pgwatch.proto
  api/types.go
  docker/Dockerfile
  docker/demo/Dockerfile
  internal/sinks/json.go
  internal/sinks/multiwriter.go
  internal/sinks/postgres.go
  internal/sinks/prometheus.go
  internal/sinks/rpc.go
  internal/sinks/rpc_test.go
  internal/sinks/types.go
Labels: enhancement, sinks

#863 [-] remove `host_config` querying from `GetSources()`
  internal/sources/postgres.go
Labels: bug

#862 [+] add basic auth support to grpc sink
  internal/sinks/rpc.go
  internal/sinks/rpc_test.go
Labels: enhancement, sinks

#869 [+] improve "Global Database Overview" dashboard
  grafana/postgres/v12/1-global-db-overview.json
  internal/metrics/metrics.yaml
Labels: dashboards

#875 [*] fix `updateSources()` query parameters number
  internal/sources/postgres.go
Labels: bug, sources
