Repository cybertec-postgresql/pgwatch, pull requests merged in 2025-03, with the labels that each got.

#665 [-] fix adding new metric to configuration db via web UI, fixes #664
  internal/metrics/postgres.go
  internal/metrics/postgres_test.go
  internal/reaper/file.go
Labels: bug, metrics, config

#670 [*] remove deprecated reaper constants
  internal/reaper/reaper.go
  internal/reaper/types.go
Labels: refactoring

#671 [*] rename `sources.MonitoredDatabase` to `SourceConn`
  internal/cmdopts/cmdsource.go
  internal/metrics/logparse.go
  internal/reaper/cache.go
  internal/reaper/database.go
  internal/reaper/reaper.go
  internal/sources/conn.go
  internal/sources/conn_test.go
  internal/sources/postgres_test.go
  internal/sources/resolver.go
  internal/sources/types.go
  internal/sources/types_test.go
Labels: refactoring

#672 [*] remove obsolete unreachable map
  internal/reaper/cache.go
  internal/reaper/database.go
  internal/reaper/reaper.go
Labels: refactoring

#673 [-] remove obsolete `undersizedDBs` and `recoveryIgnoredDBs` maps
  internal/reaper/cache.go
  internal/reaper/database.go
  internal/reaper/reaper.go
Labels: refactoring

#674 [*] replace configMap arguments with interval
  internal/metrics/logparse.go
  internal/reaper/reaper.go
Labels: refactoring

#676 [-] fix connection issues for discovered quoted db names, fixes #675
  internal/reaper/reaper.go
  internal/sources/resolver.go
Labels: bug, sources

#677 [-] remove `pg_stat_file()` dependencies from metrics
  internal/metrics/metrics.yaml
Labels: enhancement, metrics

#678 [+] add `Reaper.WriteMonitoredSources()` and `QueryMeasurents()`
  internal/reaper/cache.go
  internal/reaper/database.go
  internal/reaper/reaper.go
  internal/reaper/recommendations.go
Labels: refactoring

#686 [*] fix typo in documentation
  docs/tutorial/custom_installation.md
  docs/tutorial/upgrading.md
Labels: documentation

#685 [-] fix duplicate object key in `postgres/v11/system-stats.json`
  grafana/postgres/v11/system-stats.json
Labels: dashboards

#689 [-] fix datasource uid for Grafana v11 dashboards
  grafana/postgres/v11/1-global-db-overview.json
  grafana/postgres/v11/aws-cloudwatch.json
  grafana/postgres/v11/change-events.json
  grafana/postgres/v11/checkpointer-bgwriter-stats.json
  grafana/postgres/v11/db-overview-developer.json
  grafana/postgres/v11/db-overview-time-lag.json
  grafana/postgres/v11/db-overview.json
  grafana/postgres/v11/global-health.json
  grafana/postgres/v11/index-overview.json
  grafana/postgres/v11/lock-details.json
  grafana/postgres/v11/pgbouncer-stats.json
  grafana/postgres/v11/pgpool-stats.json
  grafana/postgres/v11/postgres-version-overview.json
  grafana/postgres/v11/recommendations.json
  grafana/postgres/v11/replication.json
  grafana/postgres/v11/server-log-events.json
  grafana/postgres/v11/sessions-overview.json
  grafana/postgres/v11/single-query-details.json
  grafana/postgres/v11/sproc-details.json
  grafana/postgres/v11/sprocs-top.json
  grafana/postgres/v11/stat-activity-realtime.json
  grafana/postgres/v11/stat-activity.json
  grafana/postgres/v11/stat-statements-sql-search.json
  grafana/postgres/v11/table-details-time-lag.json
  grafana/postgres/v11/table-details.json
  grafana/postgres/v11/tables-top.json
Labels: dashboards

#694 [*] fix old `archives.format_overrides.format` goreleaser option
  .goreleaser.yml
Labels: CI

#698 [+] bump Go to v1.24
  .github/workflows/build.yml
  .github/workflows/release.yml
  docker/Dockerfile
  docker/demo/Dockerfile
  go.mod
Labels: dependencies, go
