Repository cybertec-postgresql/pgwatch, pull requests merged in 2025-02, with the labels that each got.

#631 [-] fix concatenated output of `pgwatch metric print-init`
  internal/metrics/metrics.yaml
Labels: bug, metrics

#633 [-] fix duplicate source names in YAML configs, fixes #630
  internal/sources/types.go
  internal/sources/yaml.go
  internal/sources/yaml_test.go
Labels: bug, config

#635 [+] persist visible column settings, fixes #581
  internal/webui/src/hooks/useGridColumnVisibility.ts
  internal/webui/src/pages/MetricsPage/components/MetricsGrid/MetricsGrid.tsx
  internal/webui/src/pages/PresetsPage/components/PresetsGrid/PresetsGrid.tsx
  internal/webui/src/pages/SourcesPage/components/SourcesGrid/SourcesGrid.tsx
Labels: enhancement

#636 [-] fix checkpointer dashboards for PostgreSQL 17, fixes #613
  grafana/postgres/v10/checkpointer-bgwriter-stats.json
  grafana/postgres/v11/checkpointer-bgwriter-stats.json
Labels: dashboards

#639 [-] fix "invalid command -- ping" for PgBouncer source, closes #625
  docker/compose.postgres.yml
  docs/gallery/pgbouncer_stats.png
  go.mod
  go.sum
  grafana/postgres/v10/pgbouncer-stats.json
  grafana/postgres_datasource.yml
  internal/reaper/database.go
  internal/reaper/reaper.go
  internal/reaper/recommendations.go
  internal/sinks/postgres.go
  internal/sinks/prometheus.go
  internal/sources/types.go
Labels: bug, dashboards

#645 [-] fix updating metric definition in database configuration, fixes #644
  internal/metrics/postgres_schema.sql
Labels: bug, config

#643 [+] improve `pgwatch-demo` Docker image
  docker/bootstrap/init_dbs.sh
  docker/bootstrap/init_test_monitored_db.sh
  docker/demo/Dockerfile
  docker/demo/grafana.ini
  docker/demo/supervisord.conf
Labels: docker

#647 [+] install Grafana with `apt` in Docker and bump to v10.4.15
  docker/compose.grafana.yml
  docker/demo/Dockerfile
Labels: docker

#650 [+] allow to add EDB Postgres under monitoring, closes #649
  internal/reaper/database.go
Labels: enhancement, sources

#651 [*] use dark style logo
  grafana/postgres/v10/1-global-db-overview.json
  grafana/postgres/v10/aws-cloudwatch.json
  grafana/postgres/v10/biggest-relations.json
  grafana/postgres/v10/checkpointer-bgwriter-stats.json
  grafana/postgres/v10/db-overview-developer.json
  grafana/postgres/v10/db-overview-time-lag.json
  grafana/postgres/v10/db-overview.json
  grafana/postgres/v10/documentation.json
  grafana/postgres/v10/global-health.json
  grafana/postgres/v10/health-check.json
  grafana/postgres/v10/index-overview.json
  grafana/postgres/v10/pgbouncer-stats.json
  grafana/postgres/v10/pgpool-stats.json
  grafana/postgres/v10/postgres-version-overview.json
  grafana/postgres/v10/recommendations.json
  grafana/postgres/v10/replication.json
  grafana/postgres/v10/server-log-events.json
  grafana/postgres/v10/sessions-overview.json
  grafana/postgres/v10/show-plans-realtime.json
  grafana/postgres/v10/single-query-details.json
  grafana/postgres/v10/sprocs-top.json
  grafana/postgres/v10/stat-statements-sql-search.json
  grafana/postgres/v10/stat-statements-top-fast.json
  grafana/postgres/v10/stat-statements-top-visual.json
  grafana/postgres/v10/stat-statements-top.json
  grafana/postgres/v10/system-stats.json
  grafana/postgres/v10/table-details.json
  grafana/postgres/v10/tables-top.json
  grafana/postgres/v11/1-global-db-overview.json
  grafana/postgres/v11/aws-cloudwatch.json
  grafana/postgres/v11/biggest-relations.json
  grafana/postgres/v11/checkpointer-bgwriter-stats.json
  grafana/postgres/v11/db-overview-developer.json
  grafana/postgres/v11/db-overview-time-lag.json
  grafana/postgres/v11/db-overview.json
  grafana/postgres/v11/documentation.json
  grafana/postgres/v11/global-health.json
  grafana/postgres/v11/health-check.json
  grafana/postgres/v11/index-overview.json
  grafana/postgres/v11/pgbouncer-stats.json
  grafana/postgres/v11/pgpool-stats.json
  grafana/postgres/v11/postgres-version-overview.json
  grafana/postgres/v11/recommendations.json
  grafana/postgres/v11/replication.json
  grafana/postgres/v11/server-log-events.json
  grafana/postgres/v11/sessions-overview.json
  grafana/postgres/v11/show-plans-realtime.json
  grafana/postgres/v11/single-query-details.json
  grafana/postgres/v11/sprocs-top.json
  grafana/postgres/v11/stat-statements-sql-search.json
  grafana/postgres/v11/stat-statements-top-fast.json
  grafana/postgres/v11/stat-statements-top-visual.json
  grafana/postgres/v11/stat-statements-top.json
  grafana/postgres/v11/system-stats.json
  grafana/postgres/v11/table-details.json
  grafana/postgres/v11/tables-top.json
Labels: dashboards

#652 [-] fix linter warning "impossible condition: nil != nil"
  .golangci.yml
  internal/metrics/psutil/psutil.go
Labels: enhancement

#655 [+] add migration instructions for configuration database, closes #654
  docs/howto/config_db_bootstrap.md
  docs/howto/migrate_v2_to_v3.md
  mkdocs.yml
Labels: documentation
