Repository cybertec-postgresql/pgwatch, pull requests merged in 2025-08, with the labels that each got.

#874 [*] add note in sizing docs about metrics returning thousands of rows
  docs/howto/sizing_recommendations.md
Labels: documentation

#889 [+] allow metrics loading from folder, closes #882
  internal/metrics/yaml.go
  internal/metrics/yaml_test.go
  internal/sources/resolver_test.go
  internal/sources/yaml.go
Labels: enhancement, metrics

#900 [+] add sample metrics YAML file, closes #883
  contrib/sample.metrics.yaml
Labels: documentation, metrics

#871 [*] misc minor updates to docs
  docs/gallery/webui.md
  docs/reference/cli_env.md
  docs/reference/env_variables.md
  internal/cmdopts/cmdsource.go
  internal/webserver/cmdopts.go
Labels: documentation

#892 [*] update docs for metrics yaml folder configs
  docs/concept/installation_options.md
  docs/reference/rest.md
Labels: documentation

#899 [-] do not fail on db resolve error, just log an error, fixes #890
  internal/reaper/reaper.go
Labels: bug, sources

#903 [!] add support for PostgreSQL v18
  docker/Dockerfile.postgres-plpython3u
  internal/metrics/metrics.yaml
  internal/reaper/reaper.go
Labels: enhancement, priority, metrics

#916 [+] add "Query Performance Analysis" dashboard
  grafana/postgres/v12/4-query-performance-analysis.json
  grafana/postgres/v12/stat-activity-realtime.json
  grafana/postgres/v12/stat-activity.json
Labels: dashboards
